trash = {
    'id': '6131847734333949424',
    'from_user': {
        'id': 1427682054,
        'is_bot': False,
        'first_name': 'Sabrina Aziz Aulia',
        'username': 'SabrinaAzizAulia',
        'last_name': None,
        'language_code': 'en',
        'can_join_groups': None,
        'can_read_all_group_messages': None,
        'supports_inline_queries': None,
        'is_premium': None,
        'added_to_attachment_menu': None,
        'can_connect_to_business': None},
    'message': {
        'content_type': 'text',
        'id': 780,
        'message_id': 780,
        'from_user': <telebot.types.User object at 0x00000247445F4E50>,
        'date': 1713492130,
        'chat': <telebot.types.Chat object at 0x00000247445F4E80>,
        'sender_chat': None,
        'is_automatic_forward': None,
        'reply_to_message': None,
        'via_bot': None,
        'edit_date': None,
        'has_protected_content': None,
        'media_group_id': None,
        'author_signature': None,
        'text': 'Aneh',
        'entities': None,
        'caption_entities': None,
        'audio': None,
        'document': None,
        'photo': None,
        'sticker': None,
        'video': None,
        'video_note': None,
        'voice': None,
        'caption': None,
        'contact': None,
        'location': None,
        'venue': None,
        'animation': None,
        'dice': None,
        'new_chat_members': None,
        'left_chat_member': None,
        'new_chat_title': None,
        'new_chat_photo': None,
        'delete_chat_photo': None,
        'group_chat_created': None,
        'supergroup_chat_created': None,
        'channel_chat_created': None,
        'migrate_to_chat_id': None,
        'migrate_from_chat_id': None,
        'pinned_message': None,
        'invoice': None,
        'successful_payment': None,
        'connected_website': None,
        'reply_markup': <telebot.types.InlineKeyboardMarkup object at 0x00000247445F4E20>,
        'message_thread_id': None,
        'is_topic_message': None,
        'forum_topic_created': None,
        'forum_topic_closed': None,
        'forum_topic_reopened': None,
        'has_media_spoiler': None,
        'forum_topic_edited': None,
        'general_forum_topic_hidden': None,
        'general_forum_topic_unhidden': None,
        'write_access_allowed': None,
        'users_shared': None,
        'chat_shared': None,
        'story': None,
        'external_reply': None,
        'quote': None,
        'link_preview_options': None,
        'giveaway_created': None,
        'giveaway': None,
        'giveaway_winners': None,
        'giveaway_completed': None,
        'forward_origin': None,
        'boost_added': None,
        'sender_boost_count': None,
        'reply_to_story': None,
        'sender_business_bot': None,
        'business_connection_id': None,
        'is_from_offline': None,
        'json': {'message_id': 780,
        'from': {'id': 6614100466,
        'is_bot': True,
        'first_name': 'sabot',
        'username': 'TecsopeBot'},
        'chat': {'id': -1002055143559,
        'title': 'Games',
        'type': 'supergroup'},
        'date': 1713492130,
        'text': 'Aneh',
        'reply_markup': {'inline_keyboard': [[{'text': 'Verve',
        'callback_data': 'button_0'},
        {'text': 'Trade',
        'callback_data': 'button_1'}],
        [{'text': 'Fainted',
        'callback_data': 'button_2'},
        {'text': 'Whimsical',
        'callback_data': 'button_3'}]]}}},
    'inline_message_id': None,
    'chat_instance': '2126475195062875316',
    'data': 'button_3',
    'game_short_name': None,
    'json': {'id': '6131847734333949424',
    'from': {
        'id': 1427682054,
        'is_bot': False,
        'first_name': 'Sabrina Aziz Aulia',
        'username': 'SabrinaAzizAulia',
        'language_code': 'en'},
    'message': {'message_id': 780,
        'from': {
            'id': 6614100466,
        'is_bot': True,
        'first_name': 'sabot',
        'username': 'TecsopeBot'},
        'chat': {'id': -1002055143559,
        'title': 'Games',
        'type': 'supergroup'},
        'date': 1713492130,
        'text': 'Aneh',
        'reply_markup': {'inline_keyboard': [[{'text': 'Verve',
        'callback_data': 'button_0'},
        {'text': 'Trade',
        'callback_data': 'button_1'}],
        [{'text': 'Fainted',
        'callback_data': 'button_2'},
        {'text': 'Whimsical',
        'callback_data': 'button_3'}]]}},
    'chat_instance': '2126475195062875316',
    'data': 'button_3'}}